# Generated by Django 6.0.5 on 2026-06-03 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailconfirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('stajikori', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, default='media/default.png', null=True, upload_to='barbers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_created', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
