# Generated by Django 6.0.5 on 2026-06-03 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_barberprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aaa', to=settings.AUTH_USER_MODEL),
        ),
    ]
