# Generated by Django 6.0.5 on 2026-06-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_barberprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barberprofile',
            name='is_created',
        ),
        migrations.AddField(
            model_name='user',
            name='is_created',
            field=models.BooleanField(default=False),
        ),
    ]
