# Generated by Django 6.0.5 on 2026-06-03 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_barberprofile_is_created_user_is_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='in_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=13)),
                ('adress', models.CharField(max_length=35)),
                ('age', models.IntegerField()),
                ('img', models.ImageField(blank=True, default='media/default.png', null=True, upload_to='barbers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('in_work', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bbb', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
