# Generated by Django 6.0.5 on 2026-06-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_barberprofile_age_barberprofile_in_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberprofile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='barbers/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='barbers/'),
        ),
    ]
