# Generated by Django 6.0.5 on 2026-06-04 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_barberprofile_img_alter_userprofile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='in_work',
        ),
    ]
